"use client"
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });
import ToastContext from "@/context/ToastContext";
import Navigation  from "@/components/admin/NavBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;export default function StepperWithIcon() {

    return (
      <div className="  mt-24 z-0 bg-base-100 px-10">
      
  
    </div>
    );
  }
         
}) {
  
  return (
    <html lang="en" data-theme="light" >
      <body  className={`${inter.className} animate-dimScreen`}>
        <Provider>
         
      {children}
        <ToastContext />
        </Provider>
      </body>
    </html>
  );
}
